Tehtävä1

In [10]:
def calculate_f(a):
    lis = []
    for i in range(len(a)):
        lis.append(3 * (a[i])**2 + a[i] + 5)
    return lis
calculate_f([3,4,1])

[35, 57, 9]

Tehvtävä2

In [9]:
import numpy as np
def calculate_numpy(a):
    nx = np.array(a)
    lis = 3 * nx**2 + nx + 5
    return lis
calculate_numpy([3,4,1])

array([35, 57,  9])

Tehtävä3

In [22]:
def calculate_2df(a):
    lis = []
    for i in range(len(a)):
        lis.append(round(8 * (a[i][0])**2 + a[i][1] + 3,2))
    return lis
calculate_2df([[0.2990532, 0.73814706],[0.53660316, 0.9339861 ],[0.27658672, 0.81012994],[0.6393268, 0.63049207]])

[4.45, 6.24, 4.42, 6.9]

Tehtävä4

In [74]:
def calculate_numpy(a):
    nx = np.array(a)
    lis = np.around(8 * (nx[:,0])**2 + nx[:,1] + 3,decimals =2)
    return lis
    
calculate_numpy([[0.2990532, 0.73814706],[0.53660316, 0.9339861 ],[0.27658672, 0.81012994],[0.6393268, 0.63049207]])

array([4.45, 6.24, 4.42, 6.9 ])

Tehtävä5

In [82]:
def numsum(a):
    nx = np.array(a)
    list = 8 * (nx[:,0])**2 + nx[:,1] + 3,
    lis = np.around(np.sum(list),decimals=2)
    return lis
    
    
numsum([[0.2990532, 0.73814706],[0.53660316, 0.9339861 ],[0.27658672, 0.81012994],[0.6393268, 0.63049207]])

22.01

Testi

In [84]:
def testi(a):
    nx = np.array(a)
    return nx[:,0]
    
    
testi([[0.2990532, 0.73814706],[0.53660316, 0.9339861 ],[0.27658672, 0.81012994],[0.6393268, 0.63049207]])

array([0.2990532 , 0.53660316, 0.27658672, 0.6393268 ])